export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const INCR_PRODUCT = "INCR_PRODUCT";
export const DCR_PRODUCT = "DCR_PRODUCT";
export const UPDATE_CHECKOUT_PRICE = "UPDATE_CHECKOUT_PRICE";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
